In [1]:
import numpy as np

In [2]:
revenue = np.array([[100,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

profit = revenue - expenses
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [15]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
# matrix broadcasting
# price_per_unit = np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])

price_per_unit * units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [16]:
units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [17]:
units * price_per_unit

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [5]:
np.dot(price_per_unit, units)

# 34400 = 1000*30 + 400*5 + 1200*2

array([34400, 50000, 64400])

In [6]:
revenue = np.array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]])

revenue * 7

array([[ 7, 14, 21],
       [14, 21, 28],
       [21, 28, 35],
       [28, 35, 42]])

In [7]:
flower = np.array([[50,60,25], [10,13,5], [40,70,52]])
price_per_unit = np.array([20,30,15])

np.transpose(np.transpose(flower) * price_per_unit)

array([[1000, 1200,  500],
       [ 300,  390,  150],
       [ 600, 1050,  780]])

In [8]:
flower

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [9]:
np.transpose(price_per_unit)

array([20, 30, 15])

In [10]:
np.dot(np.transpose(price_per_unit), flower)

array([1900, 2640, 1430])